// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtX070gKp9dJMjfliDp9QxZZ-w3Zu97c',
    appId: '1:675678412878:web:774cc5de3e4545466e631f',
    messagingSenderId: '675678412878',
    projectId: 'ehr-blockchain-ee4d5',
    authDomain: 'ehr-blockchain-ee4d5.firebaseapp.com',
    storageBucket: 'ehr-blockchain-ee4d5.appspot.com',
    measurementId: 'G-9F0W0QKP07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEfR5z6629tXs3c5Zh5KXtW2B6drRsYY',
    appId: '1:675678412878:android:6f652fca0dce18836e631f',
    messagingSenderId: '675678412878',
    projectId: 'ehr-blockchain-ee4d5',
    storageBucket: 'ehr-blockchain-ee4d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8XWE4202LvTTSeSEcjAleLhSFEBOYp14',
    appId: '1:675678412878:ios:78b94766cffa81666e631f',
    messagingSenderId: '675678412878',
    projectId: 'ehr-blockchain-ee4d5',
    storageBucket: 'ehr-blockchain-ee4d5.appspot.com',
    iosClientId: '675678412878-scl2hn2ts93tddb6ov43br349ji2e836.apps.googleusercontent.com',
    iosBundleId: 'com.example.patient',
  );
}
